import type { OpportunityRecord } from "./batch";
import type { BusinessProblem } from "./diagnose";
import type { CrawledPage } from "@/backend/crawl/site-model";

/**
 * The DEMO_BRIEF: the handover from analysis to construction.
 *
 * Everything the build engine needs to produce a page for *this* business and
 * no other, and — just as important — an explicit register of what is known
 * versus what is a placeholder. A build engine that cannot tell the two apart
 * will happily invent an address, and inventing a business's address is the
 * single fastest way to destroy a sales conversation.
 *
 * Nothing here is generated by a language model. Every field is either copied
 * from verified input, derived from a measurement, or marked PLACEHOLDER.
 */

export type FactStatus = "VERIFIED" | "PROBABLE" | "PLACEHOLDER" | "UNKNOWN";

export interface BriefFact<T> {
  value: T | null;
  status: FactStatus;
  /** Where it came from, so the build engine can decide whether to show it. */
  source: string;
}

export interface BriefPage {
  path: string;
  title: string;
  purpose: string;
  /** Why this page exists at all. No page without a reason. */
  rationale: string;
  sections: string[];
  primaryCta: string;
  /** Pages this one should link to, for the internal-linking plan. */
  linksTo: string[];
  /** Whether the current site already has something equivalent. */
  existsToday: boolean;
}

export interface DemoBrief {
  business: {
    name: BriefFact<string>;
    sector: BriefFact<string>;
    city: BriefFact<string>;
    phone: BriefFact<string>;
    website: BriefFact<string>;
    rating: BriefFact<number>;
    reviewCount: BriefFact<number>;
  };
  /** What the demo must visibly beat, taken from the real diagnosis. */
  improvesOn: { problem: string; howTheDemoFixesIt: string }[];
  /** The value proposition, assembled from verified facts only. */
  valueProposition: BriefFact<string>;
  audience: BriefFact<string>;
  pages: BriefPage[];
  /** Conversion actions, ordered. First one is the page's main job. */
  conversionGoals: string[];
  seo: {
    /** Terms the business itself already uses. Not keyword research. */
    observedTerms: string[];
    titlePattern: string;
    schemaTypes: string[];
    localSeo: boolean;
  };
  design: {
    direction: string;
    rationale: string;
    /** Never invented: only what the current site actually shows. */
    observedBrandSignals: string[];
  };
  /** Fields the build engine must NOT render as fact. */
  placeholders: string[];
  /** What we do not know and would need from the client. */
  askClientFor: string[];
}

/** Sector-specific page structures. Domain knowledge, not invention. */
const SECTOR_PAGES: Record<string, { path: string; title: string; purpose: string; sections: string[]; cta: string }[]> = {
  restaurante: [
    { path: "/", title: "Inicio", purpose: "Convencer y llevar a reservar", sections: ["Presentación", "Platos destacados", "Reseñas", "Ubicación y horarios"], cta: "Reservar mesa" },
    { path: "/carta", title: "Carta", purpose: "Responder la pregunta que más se busca", sections: ["Menú por secciones", "Alérgenos", "Precios"], cta: "Reservar mesa" },
    { path: "/contacto", title: "Contacto", purpose: "Quitar cualquier fricción para llegar o llamar", sections: ["Mapa", "Teléfono", "Horarios", "Cómo llegar"], cta: "Llamar" },
  ],
  taller: [
    { path: "/", title: "Inicio", purpose: "Generar confianza y provocar la llamada", sections: ["Servicios principales", "Por qué nosotros", "Reseñas", "Ubicación"], cta: "Pedir cita" },
    { path: "/servicios", title: "Servicios", purpose: "Una página por servicio, que es como se busca", sections: ["Mecánica general", "Chapa y pintura", "Neumáticos", "Pre-ITV"], cta: "Pedir presupuesto" },
    { path: "/presupuesto", title: "Presupuesto", purpose: "Capturar la petición sin llamada", sections: ["Formulario", "Qué incluye", "Plazos"], cta: "Enviar solicitud" },
    { path: "/contacto", title: "Contacto", purpose: "Localización y horario", sections: ["Mapa", "Teléfono", "Horarios"], cta: "Llamar" },
  ],
  clinica: [
    { path: "/", title: "Inicio", purpose: "Transmitir confianza profesional", sections: ["Equipo", "Tratamientos", "Testimonios", "Instalaciones"], cta: "Pedir cita" },
    { path: "/tratamientos", title: "Tratamientos", purpose: "Una página por tratamiento", sections: ["Descripción", "Proceso", "Preguntas frecuentes"], cta: "Pedir cita" },
    { path: "/equipo", title: "Equipo", purpose: "Las personas son la razón de elegir una clínica", sections: ["Profesionales", "Titulaciones", "Experiencia"], cta: "Pedir cita" },
    { path: "/contacto", title: "Contacto", purpose: "Cita y localización", sections: ["Formulario", "Mapa", "Horarios"], cta: "Pedir cita" },
  ],
  servicios: [
    { path: "/", title: "Inicio", purpose: "Explicar qué se hace y para quién", sections: ["Servicios", "Zona de trabajo", "Reseñas", "Contacto"], cta: "Pedir presupuesto" },
    { path: "/servicios", title: "Servicios", purpose: "Detalle por servicio", sections: ["Listado", "Qué incluye", "Precios orientativos"], cta: "Pedir presupuesto" },
    { path: "/zonas", title: "Zonas", purpose: "Captar búsquedas locales por población", sections: ["Poblaciones atendidas", "Tiempos de desplazamiento"], cta: "Llamar" },
    { path: "/contacto", title: "Contacto", purpose: "Convertir", sections: ["Formulario", "Teléfono", "WhatsApp"], cta: "Pedir presupuesto" },
  ],
};

/** Maps a free-text sector onto one of the known structures. */
export function sectorTemplate(sector: string | null): keyof typeof SECTOR_PAGES {
  const value = (sector ?? "").toLowerCase();

  if (/restaurant|bar|caf|pizzer|marisqu|cocina|gastro/.test(value)) return "restaurante";
  if (/taller|mec[aá]nic|autom|neum[aá]tic|chapa/.test(value)) return "taller";
  if (/cl[ií]nic|dental|dentist|m[eé]dic|fisio|est[eé]tic|psic/.test(value)) return "clinica";
  return "servicios";
}

function fact<T>(value: T | null | undefined, status: FactStatus, source: string): BriefFact<T> {
  return { value: value ?? null, status: value === null || value === undefined ? "UNKNOWN" : status, source };
}

/** How each detected problem is answered by the demo. */
const PROBLEM_FIXES: Record<BusinessProblem["area"], string> = {
  no_contactable: "Teléfono pulsable y WhatsApp fijos en la cabecera, visibles sin hacer scroll.",
  movil_roto: "Maquetación pensada primero para el móvil, sin desbordamientos ni texto ilegible.",
  no_encontrable: "Title y meta description propios por página, encabezados jerarquizados y sitemap.",
  poco_creible: "HTTPS, reseñas reales visibles y datos del negocio a la vista.",
  inaccesible: "Etiquetas, contraste y navegación por teclado según WCAG AA.",
  estructura_rota: "Arquitectura limpia: una página por intención, sin duplicados ni enlaces rotos.",
  contenido_insuficiente: "Contenido que responde a lo que la gente busca, no relleno.",
  lento: "Imágenes optimizadas, scripts diferidos y carga diferida de lo que no se ve.",
};

/** Terms the business already uses on its own site. Observed, not researched. */
function observedTerms(pages: CrawledPage[], sector: string | null): string[] {
  const terms = new Set<string>();

  for (const page of pages) {
    if (page.state !== "OK" && page.state !== "REDIRECT") continue;
    for (const heading of page.h1) {
      const cleaned = heading.trim();
      if (cleaned.length > 3 && cleaned.length < 60) terms.add(cleaned);
    }
  }

  if (sector) terms.add(sector);
  return [...terms].slice(0, 12);
}

export interface BuildBriefOptions {
  /** Overrides the sector when the input data has none. */
  sector?: string;
}

export function buildDemoBrief(record: OpportunityRecord, options: BuildBriefOptions = {}): DemoBrief {
  const { business, problems, analysis } = record;
  const sector = business.sector ?? options.sector ?? null;
  const template = sectorTemplate(sector);
  const crawledPages = analysis?.site?.site.pages ?? [];

  const existingPaths = new Set(
    crawledPages
      .filter((page) => page.state === "OK")
      .map((page) => {
        try {
          return new URL(page.url).pathname.replace(/\.html?$/, "").replace(/\/$/, "") || "/";
        } catch {
          return page.url;
        }
      })
  );

  const pages: BriefPage[] = SECTOR_PAGES[template].map((page, index, all) => ({
    path: page.path,
    title: page.title,
    purpose: page.purpose,
    rationale:
      index === 0
        ? "Es donde aterriza la mayoría del tráfico, así que carga con la conversión principal."
        : `Responde a una intención de búsqueda propia: quien busca esto no busca lo mismo que en ${all[0].path}.`,
    sections: page.sections,
    primaryCta: page.cta,
    // Everything links back to the contact page, and the homepage links to all.
    linksTo: index === 0 ? all.slice(1).map((other) => other.path) : ["/", all[all.length - 1].path],
    existsToday: existingPaths.has(page.path),
  }));

  const placeholders: string[] = [];
  const askClientFor: string[] = [];

  if (business.phone === null) {
    placeholders.push("phone");
    askClientFor.push("Teléfono de contacto que quiere mostrar en la web.");
  }
  if (business.rating === null || business.reviewCount === null) {
    placeholders.push("reviews");
    askClientFor.push("Acceso a sus reseñas reales para poder mostrarlas (no se inventará ninguna).");
  }
  // Images are never invented. A demo shows a real photo or an obvious blank.
  placeholders.push("images");
  askClientFor.push("Fotografías reales del negocio: la demo usará marcadores hasta tenerlas.");
  askClientFor.push("Dirección postal completa y horarios exactos, para el schema de negocio local.");

  const valueProposition =
    business.rating !== null && business.reviewCount !== null && business.reviewCount >= 20
      ? fact(
          `${business.name}: ${business.rating}★ sobre ${business.reviewCount} reseñas${business.city ? ` en ${business.city}` : ""}.`,
          "VERIFIED",
          "Valoración y reseñas de los datos de entrada."
        )
      : fact<string>(null, "PLACEHOLDER", "Sin reseñas suficientes para construir una propuesta de valor verificable.");

  if (valueProposition.status === "PLACEHOLDER") placeholders.push("valueProposition");

  return {
    business: {
      name: fact(business.name, "VERIFIED", "Dato de entrada."),
      sector: fact(sector, sector ? "VERIFIED" : "UNKNOWN", "Dato de entrada."),
      city: fact(business.city, business.city ? "VERIFIED" : "UNKNOWN", "Dato de entrada."),
      phone: fact(business.phone, business.phone ? "VERIFIED" : "UNKNOWN", "Dato de entrada."),
      website: fact(business.website, business.website ? "VERIFIED" : "UNKNOWN", "Dato de entrada."),
      rating: fact(business.rating, business.rating !== null ? "VERIFIED" : "UNKNOWN", "Dato de entrada."),
      reviewCount: fact(business.reviewCount, business.reviewCount !== null ? "VERIFIED" : "UNKNOWN", "Dato de entrada."),
    },
    improvesOn: problems.map((problem) => ({
      problem: problem.statement,
      howTheDemoFixesIt: PROBLEM_FIXES[problem.area],
    })),
    valueProposition,
    audience: fact(
      sector && business.city ? `Clientes de ${sector.toLowerCase()} en ${business.city} y alrededores.` : null,
      sector && business.city ? "PROBABLE" : "UNKNOWN",
      "Inferido del sector y la localidad, no de datos de audiencia reales."
    ),
    pages,
    conversionGoals: [pages[0].primaryCta, "Llamada telefónica", "Mensaje de WhatsApp"],
    seo: {
      observedTerms: observedTerms(crawledPages, sector),
      titlePattern: business.city
        ? `{página} — ${business.name} en ${business.city}`
        : `{página} — ${business.name}`,
      schemaTypes:
        template === "restaurante"
          ? ["Restaurant", "LocalBusiness"]
          : template === "clinica"
            ? ["MedicalBusiness", "LocalBusiness"]
            : ["LocalBusiness", "Service"],
      localSeo: business.city !== null,
    },
    design: {
      direction:
        template === "restaurante"
          ? "Fotografía grande y tipografía con carácter: en hostelería la decisión es visual."
          : template === "clinica"
            ? "Sobrio, mucho blanco y jerarquía clara: la confianza se transmite con orden."
            : "Directo y funcional, con el contacto siempre visible: aquí se compra por urgencia.",
      rationale: `Elegido por el sector (${sector ?? "no especificado"}), no por gusto.`,
      observedBrandSignals: crawledPages
        .filter((page) => page.state === "OK" && page.title)
        .slice(0, 3)
        .map((page) => `Title actual: "${page.title}"`),
    },
    placeholders,
    askClientFor,
  };
}
